### PR TITLE
updated blurbs about m2g and mri analysis

### PR DESCRIPTION
**Pull request by gkiar**

### CODE REVIEW

**Comment by jovo** [comment]
@gkiar thanks dude!

**Comment by gkiar** [comment]
:smile:

## 

Greg Kiar gkiar07@gmail.com

**Comment by j6k4m8** [comment]
@g I'll be in later today (hopefully) and can show you how to meteor→docker

**Comment by gkiar** [comment]
unreal. I need access first, but that'll be great!

## 

Greg Kiar gkiar07@gmail.com

**Pull request merged**
